---
# - hosts: db
# - name: database assignment
#   import_playbook: ../static-assignments/database.yml

# - hosts: nginx
# - name: nginx assignment
#   import_playbook: ../static-assignments/nginx.yml

# - hosts: artifactory
# - name: artifactory assignment
#   import_playbook: ../static-assignments/artifactory.yml

- hosts: sonar
- name: sonar assignment
  import_playbook: ../static-assignments/sonar.yml

# - hosts: todo
# - name: Deploy the todo application
#   import_playbook: ../static-assignments/deployment.yml